import React from 'react'
import { posts } from '../data.js'
import Cards from '../components/Cards.jsx'

const Home = () => {
  return (
    <div className='flex-col p-10 justify-between'>
      {/* {posts.map((post,index)=>( <Cards post={post} key={index}/> ))} */}
      <div className='text-red-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div className='text-red-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div className='text-red-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div className='text-red-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div className='text-red-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div className='text-red-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div className='text-red-400'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
      <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur aliquid quaerat unde esse maxime magnam fugiat repudiandae modi voluptatum deleniti magni maiores voluptate inventore eaque at voluptas in explicabo nisi, doloribus numquam tempora odit!</div>
    </div>
  )
}

export default Home
